// === [ Constants ] ===========================================================

Constant
	: IntConst
	| FloatConst
	| NullConst
	| VectorConst
	| ArrayConst
	| CharArrayConst
	| StructConst
	| ZeroInitializerConst
	| GlobalIdent
	| ConstExpr
;

// --- [ integer constant ] ----------------------------------------------------

IntConst
	: IntLit
	| BoolLit
;

IntLit
	: int_lit   << astx.NewIntLit($0) >>
;

BoolLit
	: "true"    << astx.NewBoolLit($0) >>
	| "false"   << astx.NewBoolLit($0) >>
;

// --- [ floating-point constant ] ---------------------------------------------

FloatConst
	: float_lit   << astx.NewFloatLit($0) >>
;

// --- [ pointer constant ] ----------------------------------------------------

NullConst
	: "null"   << &astx.NullLit{}, nil >>
;

// --- [ vector constant ] -----------------------------------------------------

VectorConst
	: "<" Elems ">"   << astx.NewVectorConst($1) >>
;

Elems
	: empty
	| ElemList
;

ElemList
	: Elem                << astx.NewConstantList($0) >>
	| ElemList "," Elem   << astx.AppendConstant($0, $2) >>
;

Elem
	: FirstClassType Value   << astx.NewConstant($0, $1) >>
;

// --- [ array constant ] ------------------------------------------------------

ArrayConst
	: "[" Elems "]"   << astx.NewArrayConst($1) >>
;

CharArrayConst
	: "c" string_lit   << astx.NewCharArrayConst($1) >>
;

// --- [ struct constant ] -----------------------------------------------------

StructConst
	: "{" Elems "}"   << astx.NewStructConst($1) >>
;

// --- [ zero initializer constant ] -------------------------------------------

ZeroInitializerConst
	: "zeroinitializer"   << &astx.ZeroInitializerLit{}, nil >>
;

