// --- [ Binary expressions ] --------------------------------------------------

AddExpr
	: "add" "(" ConcreteType Constant "," ConcreteType Constant ")"   << astx.NewAddExpr($2, $3, $5, $6) >>
;

FAddExpr
	: "fadd" "(" ConcreteType Constant "," ConcreteType Constant ")"   << astx.NewFAddExpr($2, $3, $5, $6) >>
;

SubExpr
	: "sub" "(" ConcreteType Constant "," ConcreteType Constant ")"   << astx.NewSubExpr($2, $3, $5, $6) >>
;

FSubExpr
	: "fsub" "(" ConcreteType Constant "," ConcreteType Constant ")"   << astx.NewFSubExpr($2, $3, $5, $6) >>
;

MulExpr
	: "mul" "(" ConcreteType Constant "," ConcreteType Constant ")"   << astx.NewMulExpr($2, $3, $5, $6) >>
;

FMulExpr
	: "fmul" "(" ConcreteType Constant "," ConcreteType Constant ")"   << astx.NewFMulExpr($2, $3, $5, $6) >>
;

UDivExpr
	: "udiv" "(" ConcreteType Constant "," ConcreteType Constant ")"   << astx.NewUDivExpr($2, $3, $5, $6) >>
;

SDivExpr
	: "sdiv" "(" ConcreteType Constant "," ConcreteType Constant ")"   << astx.NewSDivExpr($2, $3, $5, $6) >>
;

FDivExpr
	: "fdiv" "(" ConcreteType Constant "," ConcreteType Constant ")"   << astx.NewFDivExpr($2, $3, $5, $6) >>
;

URemExpr
	: "urem" "(" ConcreteType Constant "," ConcreteType Constant ")"   << astx.NewURemExpr($2, $3, $5, $6) >>
;

SRemExpr
	: "srem" "(" ConcreteType Constant "," ConcreteType Constant ")"   << astx.NewSRemExpr($2, $3, $5, $6) >>
;

FRemExpr
	: "frem" "(" ConcreteType Constant "," ConcreteType Constant ")"   << astx.NewFRemExpr($2, $3, $5, $6) >>
;

