// --- [ Vector expressions ] --------------------------------------------------

ExtractElementExpr
	: "extractelement" "(" FirstClassType Constant "," FirstClassType Constant ")"   << astx.NewExtractElementExpr($2, $3, $5, $6) >>
;

InsertElementExpr
	: "insertelement" "(" FirstClassType Constant "," FirstClassType Constant "," FirstClassType Constant ")"   << astx.NewInsertElementExpr($2, $3, $5, $6, $8, $9) >>
;

ShuffleVectorExpr
	: "shufflevector" "(" FirstClassType Constant "," FirstClassType Constant "," FirstClassType Constant ")"   << astx.NewShuffleVectorExpr($2, $3, $5, $6, $8, $9) >>
;

