// --- [ Aggregate expressions ] -----------------------------------------------

ExtractValueExpr
	: "extractvalue" "(" ConcreteType Constant "," IntLitList ")"   << astx.NewExtractValueExpr($2, $3, $5) >>
;

InsertValueExpr
	: "insertvalue" "(" ConcreteType Constant "," ConcreteType Constant "," IntLitList ")"   << astx.NewInsertValueExpr($2, $3, $5, $6, $8) >>
;

