// ### [ Syntactic part ] ######################################################

<< import (
	"github.com/llir/llvm/asm/internal/ast"
	"github.com/llir/llvm/asm/internal/astx"
) >>

// === [ Modules ] =============================================================

Module
	: TopLevelDecls   << astx.NewModule($0) >>
;

TopLevelDecls
	: empty
	| TopLevelDeclList
;

TopLevelDeclList
	: TopLevelDecl                    << astx.NewTopLevelDeclList($0) >>
	| TopLevelDeclList TopLevelDecl   << astx.AppendTopLevelDecl($0, $1) >>
;

TopLevelDecl
	: SourceFilename
	| TargetSpec
	| TypeDef
	| GlobalDecl
	| GlobalDef
	| FuncDecl
	| FuncDef
	| AttrGroupDef
	| NamedMetadataDef
	| MetadataDef
;

// === [ Source filename ] =====================================================

SourceFilename
	: "source_filename" "=" string_lit   << nil, nil >>
;

// === [ Target specifiers ] ===================================================

TargetSpec
	: "target" DataLayout     << nil, nil >>
	| "target" TargetTriple   << nil, nil >>
;

DataLayout
	: "datalayout" "=" string_lit
;

TargetTriple
	: "triple" "=" string_lit
;

// === [ Type definitions ] ====================================================

TypeDef
	: LocalIdent "=" "type" Type       << astx.NewTypeDef($0, $3) >>
	| LocalIdent "=" "type" "opaque"   << astx.NewTypeDefOpaque($0) >>
;

// === [ Global variables ] ====================================================

GlobalDecl
	: GlobalIdent "=" ExternLinkage OptUnnamedAddr Immutable FirstClassType OptCommaAlign   << astx.NewGlobalDecl($0, $4, $5) >>
;

GlobalDef
	: GlobalIdent "=" OptLinkage OptUnnamedAddr Immutable FirstClassType Constant OptCommaAlign   << astx.NewGlobalDef($0, $4, $5, $6) >>
;

Immutable
	: "constant"   << true, nil >>
	| "global"     << false, nil >>
;

// === [ Functions ] ===========================================================

FuncDecl
	: "declare" OptExternLinkage FuncHeader     << $2, nil >>
;

FuncDef
	: "define" OptLinkage FuncHeader FuncBody   << astx.NewFuncDef($2, $3) >>
;

FuncHeader
	: ParamAttrs Type GlobalIdent "(" Params ")" OptUnnamedAddr FuncAttrs OptAlign   << astx.NewFuncDecl($1, $2, $4) >>
;

Params
	: empty
	| "..."                 << astx.NewParams(nil, true) >>
	| ParamList             << astx.NewParams($0, false) >>
	| ParamList "," "..."   << astx.NewParams($0, true) >>
;

ParamList
	: Param                 << astx.NewParamList($0) >>
	| ParamList "," Param   << astx.AppendParam($0, $2) >>
;

Param
	: FirstClassType ParamAttrs              << astx.NewParam($0, nil) >>
	| FirstClassType ParamAttrs LocalIdent   << astx.NewParam($0, $2) >>
;

FuncBody
	: "{" BasicBlocks "}"   << $1, nil >>
;

// === [ Attribute group definitions ] =========================================

AttrGroupDef
	: "attributes" AttrGroupID "=" "{" FuncAttrs "}"   << nil, nil >>
;

// === [ Metadata definitions ] ================================================

NamedMetadataDef
	: MetadataName "=" "!" "{" MetadataIDs "}"   << nil, nil >>
;

MetadataIDs
	: empty
	| MetadataIDList
;

MetadataIDList
	: MetadataID
	| MetadataIDList "," MetadataID
;

MetadataDef
	: MetadataID "=" OptDistinct Metadata   << nil, nil >>
;

OptDistinct
	: empty
	| "distinct"
;

Metadata
	: "!" "{" MetadataNodes "}"
;

MetadataNodes
	: empty
	| MetadataNodeList
;

MetadataNodeList
	: MetadataNode
	| MetadataNodeList "," MetadataNode
;

MetadataNode
	: Metadata
	| MetadataID
	| "!" string_lit
	| Type Constant
;

