// === [ Identifiers ] =========================================================

GlobalIdent
	: global_ident   << astx.NewGlobalIdent($0) >>
;

LocalIdent
	: local_ident   << astx.NewLocalIdent($0) >>
;

LabelIdent
	: label_ident   << astx.NewLabelIdent($0) >>
;

AttrGroupID
	: attr_group_id
;

ComdatName
	: comdat_name
;

MetadataName
	: metadata_name   << astx.NewMetadataName($0) >>
;

MetadataID
	: metadata_id   << astx.NewMetadataID($0) >>
;

