// === [ Constants ] ===========================================================

Constant
	: IntConst
	| FloatConst
	| NullConst
	| VectorConst
	| ArrayConst
	| CharArrayConst
	| StructConst
	| ZeroInitializerConst
	| GlobalIdent
	| UndefConst
	| ConstExpr
;

// --- [ Integer constant ] ----------------------------------------------------

IntConst
	: IntLit
	| BoolLit
;

IntLit
	: int_lit   << astx.NewIntLit($0) >>
;

BoolLit
	: "true"    << astx.NewBoolLit($0) >>
	| "false"   << astx.NewBoolLit($0) >>
;

// --- [ Floating-point constant ] ---------------------------------------------

FloatConst
	: float_lit   << astx.NewFloatLit($0) >>
;

// --- [ Pointer constant ] ----------------------------------------------------

NullConst
	: "null"   << &astx.NullLit{}, nil >>
;

// --- [ Vector constant ] -----------------------------------------------------

VectorConst
	: "<" ElemList ">"   << astx.NewVectorConst($1) >>
;

// --- [ Array constant ] ------------------------------------------------------

ArrayConst
	: "[" Elems "]"   << astx.NewArrayConst($1) >>
;

CharArrayConst
	: "c" string_lit   << astx.NewCharArrayConst($1) >>
;

// --- [ Struct constant ] -----------------------------------------------------

// TODO: Clean up when the parser generator no longer introduces ambiguities
// through the limitation of 1 token lookahead.
//
// Structured in this way to allow for naiive 1 token lookahead parser
// generators.
//
// Original production rule.
//
//    StructConst
//       : "{" Elems "}"
//       | "<" "{" Elems "}" ">"
//    ;
StructConst
	: "{" "}"                   << astx.NewStructConst(nil) >>
	| "{" ElemList "}"          << astx.NewStructConst($1) >>
	| "<" "{" "}" ">"           << astx.NewStructConst(nil) >>
	| "<" "{" ElemList "}" ">"  << astx.NewStructConst($2) >>
;

// --- [ Zero initializer constant ] -------------------------------------------

ZeroInitializerConst
	: "zeroinitializer"   << &astx.ZeroInitializerLit{}, nil >>
;

// --- [ Undefined value constant ] --------------------------------------------

UndefConst
	: "undef"   << &astx.UndefLit{}, nil >>
;

