// === [ Basic blocks ] ========================================================

BasicBlockList
	: BasicBlock                  << astx.NewBasicBlockList($0) >>
	| BasicBlockList BasicBlock   << astx.AppendBasicBlock($0, $1) >>
;

BasicBlock
	: OptLabelIdent Instructions Terminator   << astx.NewBasicBlock($0, $1, $2) >>
;

OptLabelIdent
	: empty
	| LabelIdent
;

