// --- [ Target specifiers ] ---------------------------------------------------

TargetSpec
	: "target" DataLayout     << $1, nil >>
	| "target" TargetTriple   << $1, nil >>
;

DataLayout
	: "datalayout" "=" string_lit   << astx.NewDataLayout($2) >>
;

TargetTriple
	: "triple" "=" string_lit   << astx.NewTargetTriple($2) >>
;

