// --- [ Comdat definitions ] --------------------------------------------------

ComdatDef
	: ComdatName "=" "comdat" SelectionKind   << nil, nil >>
;

// From spec and src of v4.0.
//
// ref: http://llvm.org/docs/LangRef.html#comdats
SelectionKind
	: "any"
	| "exactmatch"
	| "largest"
	| "noduplicates"
	| "samesize"
;

