// --- [ Functions ] -----------------------------------------------------------

FuncDecl
	: "declare" AttachedMDs OptExternLinkage FuncHeader   << astx.NewFuncDecl($1, $3) >>
;

FuncDef
	: "define" OptLinkage FuncHeader AttachedMDs FuncBody   << astx.NewFuncDef($2, $3, $4) >>
;

FuncHeader
	: OptVisibility OptDLLStorageClass OptCallConv ParamAttrs Type GlobalIdent
		"(" Params ")" OptUnnamedAddr FuncAttrs OptAlign OptComdat   << astx.NewFuncHeader($2, $4, $5, $7) >>
;

Params
	: empty
	| "..."                 << astx.NewParams(nil, true) >>
	| ParamList             << astx.NewParams($0, false) >>
	| ParamList "," "..."   << astx.NewParams($0, true) >>
;

ParamList
	: Param                 << astx.NewParamList($0) >>
	| ParamList "," Param   << astx.AppendParam($0, $2) >>
;

Param
	: FirstClassType ParamAttrs              << astx.NewParam($0, nil) >>
	| FirstClassType ParamAttrs LocalIdent   << astx.NewParam($0, $2) >>
;

FuncBody
	: "{" BasicBlocks "}"   << $1, nil >>
;

