// --- [ Metadata definitions ] ------------------------------------------------

NamedMetadataDef
	: MetadataName "=" "!" "{" MetadataIDs "}"   << astx.NewNamedMetadataDef($0, $4) >>
;

MetadataIDs
	: empty
	| MetadataIDList
;

MetadataIDList
	: MetadataID                      << astx.NewMetadataIDList($0) >>
	| MetadataIDList "," MetadataID   << astx.AppendMetadataID($0, $2) >>
;

MetadataDef
	: MetadataID "=" OptDistinct Metadata   << astx.NewMetadataDef($0, $3) >>
;

OptDistinct
	: empty
	| "distinct"
;

Metadata
	: "!" "{" MetadataNodes "}"   << astx.NewMetadata($2) >>
;

MetadataNodes
	: empty
	| MetadataNodeList
;

MetadataNodeList
	: MetadataNode                        << astx.NewMetadataNodeList($0) >>
	| MetadataNodeList "," MetadataNode   << astx.AppendMetadataNode($0, $2) >>
;

MetadataNode
	: Metadata
	| MetadataID
	| "!" string_lit   << astx.NewMetadataString($1) >>
	| Type Constant    << astx.NewConstant($0, $1) >>
;

MetadataValue
	: MetadataNode
	| ConcreteType LocalIdent   << astx.NewValue($0, $1) >>
;

