// --- [ Aggregate  instructions ] ---------------------------------------------

// ~~~ [ extractvalue ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ExtractValueInst
	: "extractvalue" ConcreteType Value "," IntLitList OptCommaAttachedMDList   << astx.NewExtractValueInst($1, $2, $4, $5) >>
;

IntLitList
	: IntLit                  << astx.NewIntLitList($0) >>
	| IntLitList "," IntLit   << astx.AppendIntLit($0, $2) >>
;

// ~~~ [ insertvalue ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

InsertValueInst
	: "insertvalue" ConcreteType Value "," ConcreteType Value "," IntLitList OptCommaAttachedMDList   << astx.NewInsertValueInst($1, $2, $4, $5, $7, $8) >>
;

