// --- [ Conversion instructions ] ---------------------------------------------

// ~~~ [ trunc ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

TruncInst
	: "trunc" ConcreteType Value "to" ConcreteType OptCommaAttachedMDList   << astx.NewTruncInst($1, $2, $4, $5) >>
;

// ~~~ [ zext ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ZExtInst
	: "zext" ConcreteType Value "to" ConcreteType OptCommaAttachedMDList   << astx.NewZExtInst($1, $2, $4, $5) >>
;

// ~~~ [ sext ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SExtInst
	: "sext" ConcreteType Value "to" ConcreteType OptCommaAttachedMDList   << astx.NewSExtInst($1, $2, $4, $5) >>
;

// ~~~ [ fptrunc ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

FPTruncInst
	: "fptrunc" ConcreteType Value "to" ConcreteType OptCommaAttachedMDList   << astx.NewFPTruncInst($1, $2, $4, $5) >>
;

// ~~~ [ fpext ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

FPExtInst
	: "fpext" ConcreteType Value "to" ConcreteType OptCommaAttachedMDList   << astx.NewFPExtInst($1, $2, $4, $5) >>
;

// ~~~ [ fptoui ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

FPToUIInst
	: "fptoui" ConcreteType Value "to" ConcreteType OptCommaAttachedMDList   << astx.NewFPToUIInst($1, $2, $4, $5) >>
;

// ~~~ [ fptosi ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

FPToSIInst
	: "fptosi" ConcreteType Value "to" ConcreteType OptCommaAttachedMDList   << astx.NewFPToSIInst($1, $2, $4, $5) >>
;

// ~~~ [ uitofp ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

UIToFPInst
	: "uitofp" ConcreteType Value "to" ConcreteType OptCommaAttachedMDList   << astx.NewUIToFPInst($1, $2, $4, $5) >>
;

// ~~~ [ sitofp ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SIToFPInst
	: "sitofp" ConcreteType Value "to" ConcreteType OptCommaAttachedMDList   << astx.NewSIToFPInst($1, $2, $4, $5) >>
;

// ~~~ [ ptrtoint ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

PtrToIntInst
	: "ptrtoint" ConcreteType Value "to" ConcreteType OptCommaAttachedMDList   << astx.NewPtrToIntInst($1, $2, $4, $5) >>
;

// ~~~ [ inttoptr ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

IntToPtrInst
	: "inttoptr" ConcreteType Value "to" ConcreteType OptCommaAttachedMDList   << astx.NewIntToPtrInst($1, $2, $4, $5) >>
;

// ~~~ [ bitcast ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

BitCastInst
	: "bitcast" ConcreteType Value "to" ConcreteType OptCommaAttachedMDList   << astx.NewBitCastInst($1, $2, $4, $5) >>
;

// ~~~ [ addrspacecast ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

AddrSpaceCastInst
	: "addrspacecast" ConcreteType Value "to" ConcreteType OptCommaAttachedMDList   << astx.NewAddrSpaceCastInst($1, $2, $4, $5) >>
;

