// ~~~ [ Target Definition ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// https://llvm.org/docs/LangRef.html#target-triple
// https://llvm.org/docs/LangRef.html#data-layout

// ref: ParseTargetDefinition
//
//   ::= 'target' 'triple' '=' STRINGCONSTANT
//   ::= 'target' 'datalayout' '=' STRINGCONSTANT

TargetDefinition
	: "target" "datalayout" "=" StringLit
	<< &ir.DataLayout{DataLayout: $3.(string)}, nil >>
	| "target" "triple" "=" StringLit
	<< &ir.TargetTriple{TargetTriple: $3.(string)}, nil >>
;

